apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coherence-fund-worker
  namespace: coherence-fund
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: coherence-fund-worker

