"""Regression tests for the red-team adversarial harness (prompt 13).

These tests run the curated adversarial suite under
``tests/adversarial/`` through the production
``ScoringService + DecisionPolicyService`` chain and assert that:

1. The deterministic confusion matrix matches a **pinned** expected
   matrix. Any drift in scoring / decision-policy behavior will fail
   this test loudly with a clear diff. When such drift is intentional,
   bump the pin per the guidance in
   ``docs/specs/red_team_harness.md``.
2. The CLI ``red-team-run`` subcommand returns the documented exit
   codes (``0`` all-match, ``1`` any-mismatch, ``2`` fixture / labels
   load error).
3. The harness honors its no-network / offline guarantees (asserted
   indirectly: ``ScoringService`` is configured with the local
   ``tfidf`` embedder + ``heuristic`` contradiction backend, and the
   harness performs no DB writes).

These tests must run fully offline. They do **not** carry a network
marker (per the prompt 13 prohibition).
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from coherence_engine.server.fund.services.decision_policy import (
    DECISION_POLICY_VERSION,
)
from coherence_engine.server.fund.services.red_team import (
    CANONICAL_VERDICTS,
    RedTeamError,
    canonicalize_verdict,
    load_fixtures,
    load_labels,
    run_adversarial_suite,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
COHERENCE_PKG_ROOT = Path(__file__).resolve().parents[1]
FIXTURES_DIR = COHERENCE_PKG_ROOT / "tests" / "adversarial" / "fixtures"
LABELS_PATH = COHERENCE_PKG_ROOT / "tests" / "adversarial" / "labels.json"


# ---------------------------------------------------------------------------
# Pinned regression baseline
# ---------------------------------------------------------------------------
#
# This is the snapshot of the *current* end-to-end behavior of the
# scoring + decision pipeline against the 12 fixtures. The harness's
# job is to flag drift, not to assert "good" behavior — when the
# scorer / decision policy changes intentionally, this matrix MUST be
# regenerated by re-running ``run_adversarial_suite`` and the change
# justified in ``docs/specs/red_team_harness.md``.
#
# Outer key:  expected_verdict (ground truth from labels.json)
# Inner key:  actual_verdict   (canonicalized policy output)
EXPECTED_CONFUSION_MATRIX = {
    "manual_review": {"manual_review": 0, "pass": 0, "reject": 4},
    "pass": {"manual_review": 0, "pass": 0, "reject": 4},
    "reject": {"manual_review": 0, "pass": 0, "reject": 4},
}

EXPECTED_TOTALS = {
    "total_cases": 12,
    "matches": 4,
    "mismatches": 8,
    "false_pass": 0,
    "false_reject": 8,
    "false_review": 0,
}

EXPECTED_FIXTURE_COUNT = 12


# ---------------------------------------------------------------------------
# Fixture / label hygiene
# ---------------------------------------------------------------------------


def test_fixtures_directory_has_at_least_twelve_cases():
    fixtures = load_fixtures(FIXTURES_DIR)
    assert len(fixtures) >= EXPECTED_FIXTURE_COUNT


def test_fixtures_cover_all_required_categories():
    fixtures = load_fixtures(FIXTURES_DIR)
    by_category = {}
    for f in fixtures:
        by_category.setdefault(f["category"], 0)
        by_category[f["category"]] += 1
    assert by_category.get("incoherent", 0) >= 4
    assert by_category.get("coherent_evidenced", 0) >= 4
    assert by_category.get("template_echo", 0) >= 2
    assert by_category.get("borderline", 0) >= 2


def test_every_fixture_has_a_label():
    fixtures = load_fixtures(FIXTURES_DIR)
    labels = load_labels(LABELS_PATH)
    for f in fixtures:
        assert f["_path"].name in labels, f"missing label for {f['_path'].name}"
    assert set(labels) == {f["_path"].name for f in fixtures}


def test_label_verdicts_are_in_canonical_set():
    labels = load_labels(LABELS_PATH)
    for basename, entry in labels.items():
        assert entry["expected_verdict"] in CANONICAL_VERDICTS, basename


def test_canonicalize_verdict_translates_fail_to_reject():
    assert canonicalize_verdict("fail") == "reject"
    assert canonicalize_verdict("pass") == "pass"
    assert canonicalize_verdict("manual_review") == "manual_review"


# ---------------------------------------------------------------------------
# Pinned-matrix regression test
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def red_team_report():
    return run_adversarial_suite(
        fixtures_dir=FIXTURES_DIR,
        labels_path=LABELS_PATH,
        policy_version=DECISION_POLICY_VERSION,
    )


def test_confusion_matrix_matches_pinned_baseline(red_team_report):
    actual = red_team_report.to_canonical_dict()["confusion_matrix"]
    assert actual == EXPECTED_CONFUSION_MATRIX, (
        "Red-team confusion matrix drifted. If this change is "
        "intentional, regenerate the matrix per "
        "docs/specs/red_team_harness.md and bump "
        "EXPECTED_CONFUSION_MATRIX in tests/test_red_team_harness.py.\n"
        f"expected: {EXPECTED_CONFUSION_MATRIX}\n"
        f"actual:   {actual}"
    )


def test_aggregate_counts_match_pinned_baseline(red_team_report):
    payload = red_team_report.to_canonical_dict()
    assert payload["total_cases"] == EXPECTED_TOTALS["total_cases"]
    assert payload["matches"] == EXPECTED_TOTALS["matches"]
    assert payload["mismatches"] == EXPECTED_TOTALS["mismatches"]
    assert payload["counts"]["false_pass"] == EXPECTED_TOTALS["false_pass"]
    assert payload["counts"]["false_reject"] == EXPECTED_TOTALS["false_reject"]
    assert payload["counts"]["false_review"] == EXPECTED_TOTALS["false_review"]


def test_report_is_byte_deterministic_across_runs():
    """Two consecutive runs of the suite must produce byte-identical output."""
    a = run_adversarial_suite(
        fixtures_dir=FIXTURES_DIR,
        labels_path=LABELS_PATH,
        policy_version=DECISION_POLICY_VERSION,
    ).to_canonical_bytes()
    b = run_adversarial_suite(
        fixtures_dir=FIXTURES_DIR,
        labels_path=LABELS_PATH,
        policy_version=DECISION_POLICY_VERSION,
    ).to_canonical_bytes()
    assert a == b


def test_report_records_decision_policy_version(red_team_report):
    payload = red_team_report.to_canonical_dict()
    assert payload["decision_policy_version"] == DECISION_POLICY_VERSION
    assert payload["schema_version"] == "red-team-report-v1"


def test_per_case_results_include_all_fixtures(red_team_report):
    payload = red_team_report.to_canonical_dict()
    cases = payload["cases"]
    assert len(cases) == EXPECTED_FIXTURE_COUNT
    fixture_basenames = sorted(p.name for p in FIXTURES_DIR.glob("*.json"))
    assert sorted(c["fixture_filename"] for c in cases) == fixture_basenames


# ---------------------------------------------------------------------------
# RedTeamError surfaces (CLI exit-code-2 path)
# ---------------------------------------------------------------------------


def test_run_adversarial_suite_raises_on_missing_fixtures_dir(tmp_path):
    missing = tmp_path / "no_such_dir"
    with pytest.raises(RedTeamError):
        run_adversarial_suite(
            fixtures_dir=missing,
            labels_path=LABELS_PATH,
            policy_version=DECISION_POLICY_VERSION,
        )


def test_run_adversarial_suite_raises_on_missing_labels(tmp_path):
    missing_labels = tmp_path / "no_such_labels.json"
    with pytest.raises(RedTeamError):
        run_adversarial_suite(
            fixtures_dir=FIXTURES_DIR,
            labels_path=missing_labels,
            policy_version=DECISION_POLICY_VERSION,
        )


def test_run_adversarial_suite_raises_on_policy_version_mismatch():
    with pytest.raises(RedTeamError) as exc_info:
        run_adversarial_suite(
            fixtures_dir=FIXTURES_DIR,
            labels_path=LABELS_PATH,
            policy_version="decision-policy-v999",
        )
    assert "decision_policy_version_pin_mismatch" in str(exc_info.value)


def test_run_adversarial_suite_raises_on_unlabeled_fixture(tmp_path):
    # Copy a single fixture but provide an empty labels.json.
    fixture_src = next(FIXTURES_DIR.glob("*.json"))
    fx_dir = tmp_path / "fixtures"
    fx_dir.mkdir()
    (fx_dir / fixture_src.name).write_text(
        fixture_src.read_text(encoding="utf-8"), encoding="utf-8"
    )
    labels = tmp_path / "labels.json"
    labels.write_text("{}", encoding="utf-8")
    with pytest.raises(RedTeamError):
        run_adversarial_suite(
            fixtures_dir=fx_dir,
            labels_path=labels,
            policy_version=DECISION_POLICY_VERSION,
        )


def test_load_labels_rejects_unknown_verdict(tmp_path):
    labels = tmp_path / "labels.json"
    labels.write_text(
        json.dumps({"foo.json": {"expected_verdict": "invest"}}),
        encoding="utf-8",
    )
    with pytest.raises(RedTeamError):
        load_labels(labels)


# ---------------------------------------------------------------------------
# CLI integration: red-team-run exit codes
# ---------------------------------------------------------------------------


def _cli_env():
    env = os.environ.copy()
    env.setdefault("PYTHONPATH", str(REPO_ROOT))
    return env


def test_cli_red_team_run_exits_one_on_mismatch(tmp_path):
    """Current pinned behavior includes 8 mismatches -> exit 1."""
    out_path = tmp_path / "report.json"
    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "coherence_engine",
            "red-team-run",
            "--fixtures-dir",
            str(FIXTURES_DIR),
            "--labels",
            str(LABELS_PATH),
            "--output",
            str(out_path),
        ],
        cwd=str(REPO_ROOT),
        env=_cli_env(),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 1, (
        f"expected exit 1 (mismatch), got {proc.returncode}\n"
        f"stdout: {proc.stdout}\nstderr: {proc.stderr}"
    )
    assert out_path.exists()
    payload = json.loads(out_path.read_text(encoding="utf-8"))
    assert payload["mismatches"] == EXPECTED_TOTALS["mismatches"]
    assert payload["confusion_matrix"] == EXPECTED_CONFUSION_MATRIX


def test_cli_red_team_run_exits_two_on_missing_fixtures_dir(tmp_path):
    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "coherence_engine",
            "red-team-run",
            "--fixtures-dir",
            str(tmp_path / "no_such_dir"),
            "--labels",
            str(LABELS_PATH),
        ],
        cwd=str(REPO_ROOT),
        env=_cli_env(),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 2, (
        f"expected exit 2 (load error), got {proc.returncode}\n"
        f"stdout: {proc.stdout}\nstderr: {proc.stderr}"
    )
    assert "Error" in proc.stderr


def test_cli_red_team_run_exits_two_on_policy_version_pin_mismatch(tmp_path):
    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "coherence_engine",
            "red-team-run",
            "--fixtures-dir",
            str(FIXTURES_DIR),
            "--labels",
            str(LABELS_PATH),
            "--policy-version",
            "decision-policy-v999",
        ],
        cwd=str(REPO_ROOT),
        env=_cli_env(),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 2
    assert "decision_policy_version_pin_mismatch" in proc.stderr


def test_cli_red_team_run_exits_zero_when_all_labels_match(tmp_path):
    """If we relabel every fixture to its currently-observed actual verdict,
    the CLI should exit 0. This guards against the exit-code logic itself
    inverting in a regression."""
    report = run_adversarial_suite(
        fixtures_dir=FIXTURES_DIR,
        labels_path=LABELS_PATH,
        policy_version=DECISION_POLICY_VERSION,
    )
    aligned_labels = {
        c.fixture_filename: {
            "expected_verdict": c.actual_verdict,
            "rationale": "aligned-to-current-output for exit-code test",
        }
        for c in report.cases
    }
    aligned_path = tmp_path / "labels_aligned.json"
    aligned_path.write_text(json.dumps(aligned_labels), encoding="utf-8")

    proc = subprocess.run(
        [
            sys.executable,
            "-m",
            "coherence_engine",
            "red-team-run",
            "--fixtures-dir",
            str(FIXTURES_DIR),
            "--labels",
            str(aligned_path),
        ],
        cwd=str(REPO_ROOT),
        env=_cli_env(),
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, (
        f"expected exit 0 (all match), got {proc.returncode}\n"
        f"stdout: {proc.stdout[:500]}\nstderr: {proc.stderr}"
    )
