apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coherence-fund.fullname" . }}-secrets
type: Opaque
stringData:
{{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | quote }}
{{- end }}

