apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coherence-fund-prod
resources:
  - ../../base
patchesStrategicMerge:
  - patch-config.yaml
  - patch-secret.yaml
  - patch-deployments.yaml
  - patch-hpa.yaml
  - patch-pdb.yaml
  - patch-networkpolicy.yaml
