apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coherence-fund-api
spec:
  minAvailable: 2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coherence-fund-worker
spec:
  minAvailable: 1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coherence-fund-scoring-worker
spec:
  minAvailable: 1

